package fahrtabruf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-04T13:29:07.783+02:00
 * Generated source version: 3.3.1
 *
 */
@WebServiceClient(name = "RueckmeldungService",
                  wsdlLocation = "http://localhost:8080/TaxiWebService/services/RueckmeldungPort?wsdl",
                  targetNamespace = "http://fahrtabruf/")
public class RueckmeldungService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://fahrtabruf/", "RueckmeldungService");
    public final static QName RueckmeldungPort = new QName("http://fahrtabruf/", "RueckmeldungPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/TaxiWebService/services/RueckmeldungPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RueckmeldungService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/TaxiWebService/services/RueckmeldungPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RueckmeldungService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RueckmeldungService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RueckmeldungService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public RueckmeldungService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RueckmeldungService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RueckmeldungService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns RueckmeldungSEI
     */
    @WebEndpoint(name = "RueckmeldungPort")
    public RueckmeldungSEI getRueckmeldungPort() {
        return super.getPort(RueckmeldungPort, RueckmeldungSEI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RueckmeldungSEI
     */
    @WebEndpoint(name = "RueckmeldungPort")
    public RueckmeldungSEI getRueckmeldungPort(WebServiceFeature... features) {
        return super.getPort(RueckmeldungPort, RueckmeldungSEI.class, features);
    }

}
