
package fahrtabruf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-04T13:29:07.736+02:00
 * Generated source version: 3.3.1
 *
 */
public final class RueckmeldungSEI_RueckmeldungPort_Client {

    private static final QName SERVICE_NAME = new QName("http://fahrtabruf/", "RueckmeldungService");

    private RueckmeldungSEI_RueckmeldungPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RueckmeldungService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        RueckmeldungService ss = new RueckmeldungService(wsdlURL, SERVICE_NAME);
        RueckmeldungSEI port = ss.getRueckmeldungPort();

        {
        System.out.println("Invoking getFahrtlisteMitDatum...");
        int _getFahrtlisteMitDatum_arg0 = -724097570;
        java.util.List<fahrtabruf.Taxi> _getFahrtlisteMitDatum__return = port.getFahrtlisteMitDatum(_getFahrtlisteMitDatum_arg0);
        System.out.println("getFahrtlisteMitDatum.result=" + _getFahrtlisteMitDatum__return);


        }

        System.exit(0);
    }

}
