
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fahrtabruf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-04T13:29:07.768+02:00
 * Generated source version: 3.3.1
 *
 */

@javax.jws.WebService(
                      serviceName = "RueckmeldungService",
                      portName = "RueckmeldungPort",
                      targetNamespace = "http://fahrtabruf/",
                      wsdlLocation = "http://localhost:8080/TaxiWebService/services/RueckmeldungPort?wsdl",
                      endpointInterface = "fahrtabruf.RueckmeldungSEI")

public class RueckmeldungPortImpl implements RueckmeldungSEI {

    private static final Logger LOG = Logger.getLogger(RueckmeldungPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fahrtabruf.RueckmeldungSEI#getFahrtlisteMitDatum(int arg0)*
     */
    public java.util.List<fahrtabruf.Taxi> getFahrtlisteMitDatum(int arg0) {
        LOG.info("Executing operation getFahrtlisteMitDatum");
        System.out.println(arg0);
        try {
            java.util.List<fahrtabruf.Taxi> _return = new java.util.ArrayList<fahrtabruf.Taxi>();
            fahrtabruf.Taxi _returnVal1 = new fahrtabruf.Taxi();
            _returnVal1.setCusId(-135655458);
            _returnVal1.setDatum(989931316);
            _returnVal1.setGefahreneKm(1321515744);
            _returnVal1.setNachOrt("NachOrt1464263218");
            _returnVal1.setVonOrt("VonOrt-801016785");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
