package fahrtabruf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-04T13:29:07.783+02:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://fahrtabruf/", name = "RueckmeldungSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface RueckmeldungSEI {

    @WebMethod(action = "urn:GetFahrtlisteMitDatum")
    @RequestWrapper(localName = "getFahrtlisteMitDatum", targetNamespace = "http://fahrtabruf/", className = "fahrtabruf.GetFahrtlisteMitDatum")
    @ResponseWrapper(localName = "getFahrtlisteMitDatumResponse", targetNamespace = "http://fahrtabruf/", className = "fahrtabruf.GetFahrtlisteMitDatumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fahrtabruf.Taxi> getFahrtlisteMitDatum(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
