
package fahrtabruf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.1
 * Thu Apr 04 13:22:45 CEST 2019
 * Generated source version: 3.3.1
 */

@XmlRootElement(name = "getFahrtlisteMitDatumResponse", namespace = "http://fahrtabruf/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getFahrtlisteMitDatumResponse", namespace = "http://fahrtabruf/")

public class GetFahrtlisteMitDatumResponse {

    @XmlElement(name = "return")
    private java.util.ArrayList<bean.Taxi> _return;

    public java.util.ArrayList<bean.Taxi> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.ArrayList<bean.Taxi> new_return)  {
        this._return = new_return;
    }

}

