package com.sap.persistence.j;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-04T13:34:19.983+02:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://sap.com/persistence/j/", name = "Jcus")
@XmlSeeAlso({ObjectFactory.class})
public interface Jcus {

    @WebMethod
    @RequestWrapper(localName = "findAllCUSTOMER", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.FindAllCUSTOMER")
    @ResponseWrapper(localName = "findAllCUSTOMERResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.FindAllCUSTOMERResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sap.persistence.j.Customer> findAllCUSTOMER();

    @WebMethod
    @RequestWrapper(localName = "findCUSTOMERByCusId", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.FindCUSTOMERByCusId")
    @ResponseWrapper(localName = "findCUSTOMERByCusIdResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.FindCUSTOMERByCusIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.sap.persistence.j.Customer> findCUSTOMERByCusId(
        @WebParam(name = "cusId", targetNamespace = "")
        java.lang.Integer cusId
    );

    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.DeleteResponse")
    public void delete(
        @WebParam(name = "entity", targetNamespace = "")
        com.sap.persistence.j.Customer entity
    );

    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.CreateResponse")
    public void create(
        @WebParam(name = "entity", targetNamespace = "")
        com.sap.persistence.j.Customer entity
    );

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.UpdateResponse")
    public void update(
        @WebParam(name = "entity", targetNamespace = "")
        com.sap.persistence.j.Customer entity
    );

    @WebMethod
    @RequestWrapper(localName = "getCUSTOMERItemCount", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.GetCUSTOMERItemCount")
    @ResponseWrapper(localName = "getCUSTOMERItemCountResponse", targetNamespace = "http://sap.com/persistence/j/", className = "com.sap.persistence.j.GetCUSTOMERItemCountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getCUSTOMERItemCount();
}
